# Generated by Django 3.1.13 on 2022-11-22 07:41

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('cron', models.TextField()),
                ('priority', models.IntegerField()),
                ('sequence', models.IntegerField()),
            ],
            options={
                'db_table': 'schedules',
                'ordering': ['-_id'],
            },
        ),
    ]
