# Use root/example as user/password credentials
version: '3.5'

services:
  mongo:
    image: mongo:5.0.3
    # ports:
    #   - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
    network_mode: "host"

  mongo-express:
    image: "mongo-express:0.54"
    # ports:
    #   - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: localhost
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
    network_mode: "host"
    depends_on:
      - mongo