# Generated by Django 3.1.13 on 2022-07-19 09:05

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('user_id', models.TextField()),
                ('workbook_id', models.TextField()),
                ('correct_rate', models.IntegerField()),
                ('correct_count', models.IntegerField()),
                ('correct_count_all', models.IntegerField()),
                ('page_done', models.IntegerField()),
                ('page_today', djongo.models.fields.JSONField()),
                ('page_tomorrow', djongo.models.fields.JSONField()),
                ('person_type', models.TextField()),
                ('history', djongo.models.fields.JSONField()),
                ('ext', djongo.models.fields.JSONField()),
                ('reg_date', models.DateTimeField()),
                ('reg_id', models.TextField()),
                ('mod_date', models.DateTimeField()),
                ('mod_id', models.TextField()),
            ],
            options={
                'db_table': 'students',
                'ordering': ['-_id'],
            },
        ),
    ]
